server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/goodym_hotel?useUnicode=true
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root